kubectl delete job kube-bench || true &&  cat <<EOF | kubectl create -f -
apiVersion: batch/v1
kind: Job
metadata:
  name: kube-bench
spec:
  template:
    spec:
      hostPID: true
      containers:
        - name: kube-bench
          # Push the image to your ECR and then refer to it here
          # image: <ID.dkr.ecr.region.amazonaws.com/aquasec/kube-bench:ref>
          image: aquasec/kube-bench:latest
          # To send findings to AWS Security Hub, refer to `Elastic Kubernetes Service - With ASFF.yaml` instead
          command: [ "/bin/sh" ]
          args: [ "-c", "apk add curl && kube-bench run --targets node --benchmark eks-1.0 --json | curl -s -H \"Content-Type: application/json\" -X POST --data-binary @- {SITE URL HERE}/api/kube-bench/{CLUSTER ID ETC HERE}" ]
          volumeMounts:
            - name: var-lib-kubelet
              mountPath: /var/lib/kubelet
              readOnly: true
            - name: etc-systemd
              mountPath: /etc/systemd
              readOnly: true
            - name: etc-kubernetes
              mountPath: /etc/kubernetes
              readOnly: true
      restartPolicy: Never
      volumes:
        - name: var-lib-kubelet
          hostPath:
            path: "/var/lib/kubelet"
        - name: etc-systemd
          hostPath:
            path: "/etc/systemd"
        - name: etc-kubernetes
          hostPath:
            path: "/etc/kubernetes"
EOF
