name: Docker Build

on:
  workflow_call:
    inputs:
      dash-image-tags:
        required: true
        type: string
      trawler-image-tags:
        required: true
        type: string
      push-images:
        required: false
        type: boolean
        default: true

jobs:
  docker_dash:
    name: Build Dash Image
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          config-inline: |
            [registry."docker.io"]
              mirrors = ["public-docker.nexus.celestialdata.net"]

      - name: Login to GHCR
        uses: docker/login-action@v2
        if: inputs.push-images
        with:
          registry: ghcr.io
          username: m9sweeper
          password: ${{ github.token }}

      - name: Build & Push Dash
        uses: docker/build-push-action@v4
        if: inputs.push-images
        with:
          context: .
          push: true
          provenance: false
          tags: ${{ inputs.dash-image-tags }}
          cache-from: type=gha,scope=build-dash
          cache-to: type=gha,mode=max,scope=build-dash

      - name: Build & Export Dash
        uses: docker/build-push-action@v4
        if: inputs.push-images == false
        with:
          context: .
          push: false
          provenance: false
          tags: ${{ inputs.dash-image-tags }}
          cache-from: type=gha,scope=build-dash
          cache-to: type=gha,mode=max,scope=build-dash
          outputs: type=docker,dest=dash.tar

      - name: Upload Dash Image Archive
        uses: actions/upload-artifact@v3
        if: inputs.push-images == false
        with:
          path: dash.tar
          name: dash
          retention-days: 5

      - name: Cleanup Work Directory
        uses: AutoModality/action-clean@v1
        if: always()

  docker_trawler:
    name: Build Trawler Image
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          config-inline: |
            [registry."docker.io"]
              mirrors = ["public-docker.nexus.celestialdata.net"]

      - name: Login to GHCR
        uses: docker/login-action@v2
        if: inputs.push-images
        with:
          registry: ghcr.io
          username: m9sweeper
          password: ${{ github.token }}

      - name: Build & Push Trawler
        uses: docker/build-push-action@v4
        if: inputs.push-images
        with:
          context: trawler/
          push: true
          provenance: false
          tags: ${{ inputs.trawler-image-tags }}
          cache-from: type=gha,scope=build-trawler
          cache-to: type=gha,mode=max,scope=build-trawler

      - name: Build & Export Trawler
        uses: docker/build-push-action@v4
        if: inputs.push-images == false
        with:
          context: trawler/
          push: false
          provenance: false
          tags: ${{ inputs.trawler-image-tags }}
          cache-from: type=gha,scope=build-trawler-amd64
          cache-to: type=gha,mode=max,scope=build-trawler-amd64
          outputs: type=docker,dest=trawler.tar

      - name: Upload Trawler Image Archive
        uses: actions/upload-artifact@v3
        if: inputs.push-images == false
        with:
          path: trawler.tar
          name: trawler
          retention-days: 5

      - name: Cleanup Work Directory
        uses: AutoModality/action-clean@v1
        if: always()